apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  labels:
    app: helm-{{ .Chart.Name }}

data:
  apiConfig.js: |
   window.endpointConfig = {
    local: {
    SERVICES_BASE_URL: "http://localhost:8080", }
    }
