FROM eclipse-temurin:17

RUN adduser -u 8877 appuser -disabled-password
USER appuser

WORKDIR /app

COPY target/*.jar app.jar
COPY src/main/resources/application.properties /app/application.properties
EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar", "--spring.config.location=file:/app/application.properties"]
