version: "3.8"

networks:
  monitoring:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/rateme_swtp
      - SPRING_DATASOURCE_USERNAME=root
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - 8080:8080
  frontend:
    build:
      context: .
      dockerfile: "Dockerfile.ui"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - 8082:80
  database:
    build:
      context: .
      dockerfile: "Dockerfile.database"
    volumes:
      - ./database/DbVolume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=rateme_swtp
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
