apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-{{ .Chart.Name }}
  labels:
    app: database
spec:
  selector:
    matchLabels:
      app: database
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
        tier: mysql
    spec:
      containers:
        - image: {{ include "database.image" . | quote }}
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: rateme_swtp
      
            - name: MYSQL_USER
              value: myuser
              # valueFrom:
              #   secretKeyRef:
              #     name: db-security
              #     key: user
            - name: MYSQL_PASSWORD
              value: test
              # valueFrom:
              #   secretKeyRef:
              #     name: db-security
              #     key: password
            - name: MYSQL_HOST
              value: helm-database-service
            - name: MYSQL_ROOT_PASSWORD
              # valueFrom:
              #   secretKeyRef:
              #     name: secret-to-be-created
              #     key: password_file
              value: test
          ports:
            - containerPort: {{ .Values.database.containerPort }}
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc