apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-{{ .Chart.Name }}
  labels:
    app: database
spec:
  selector:
    matchLabels:
      app: database
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
        tier: mysql
    spec:
      containers:
        - image: ghcr.io/goldjns/rateme-nextgen-database:v1.10.3-beta
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: rateme_swtp
      
            - name: MYSQL_USER
              value: custom
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-to-be-created
                  key: password_file
            - name: MYSQL_HOST
              value: helm-database-service
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-to-be-created
                  key: password_file
          ports:
            - containerPort: {{ .Values.database.containerPort }}
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc