name: Helm deployments
inputs:
  environment:
    required: true
on:
  workflow_dispatch:

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        project_id: ${{ secrets.GKE_PROJECT }}

    - uses: simenandre/setup-gke-gcloud-auth-plugin@v1

    - uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: rateme-nextgen-cluster
        location: us-central1
    - name: Deploy
      uses: WyriHaximus/github-action-helm3@v3
      with:
        exec: cd deployment && chmod go-r ~/.kube/config && chmod +x ./deployAll.sh && ./deployAll.sh $NAMESPACE
        kubeconfig: "${{ secrets.KUBECONFIG }}"
        overrule_existing_kubeconfig: "true"
