name: Helm deployments
description: Generic step for helm deployments
inputs:
  environment:
    description: The environment to deploy to
    required: true

runs:
  using: "composite"
  steps:
    - name: Terraform Init
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      shell: bash

    - name: Terraform Plan
      run: terraform plan -input=false -lock=false
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      shell: bash
    - name: Terraform Apply
      #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false -lock=false
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      shell: bash
