name: Helm deployments
description: Generic step for helm deployments
inputs:
  environment:
    description: The environment to deploy to
    required: true

runs:
  using: "composite"
  steps:
    - name: Terraform Init
      uses: actions/checkout@v3
    - name: Authenticate to GCP
      env:
        GOOGLE_CREDENTIALS: ${{ inputs.googlecredentials }}
        GKE_PROJECT: ${{ inputs.googleproject }}
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.googlecredentials }}
        project_id: ${{ inputs.googleproject }}

    - uses: simenandre/setup-gke-gcloud-auth-plugin@v1

    - uses: google-github-actions/get-gke-credentials@v1
      with:
        cluster_name: rateme-nextgen-cluster
        location: us-central1-c
      run: terraform init
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      shell: bash

    - name: Terraform Plan
      run: terraform plan -input=false -lock=false
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      shell: bash
    - name: Terraform Apply
      #if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false -lock=false
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      shell: bash
