apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rateme-nextgen-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: gce
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: "gce"
  rules:
    - http:
        paths:
          - path: / # Path for the frontend service
            pathType: Prefix
            backend:
              service:
                name: helm-ui-service
                port:
                  number: 80
