apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: MyIngress
  namespace: default
spec:
  rules:
    - host: rateme-nextgen.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: helm-ui-service
                port:
                  name: httpui
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: helm-backend-service
                port:
                  name: httpbackend
# spec:
#   defaultBackend:
#     service:
#       name: helm-backend-service
#       port:
#         number: 3000

# ---
# apiVersion: cloud.google.com/v1
# kind: BackendConfig
# metadata:
#   name: my-backendconfig
# spec:
#   timeoutSec: 120

# ---
# apiVersion: networking.gke.io/v1beta1
# kind: FrontendConfig
# metadata:
#   name: ssl-redirect
# spec:
#   redirectToHttps:
#     enabled: true

# ---
# apiVersion: networking.gke.io/v1
# kind: ManagedCertificate
# metadata:
#   name: managed-cert
# spec:
#   domains:
#     - subdomain.put-your-domain-here.com

# ---

