apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config-map
data:
  mysql-server: database-service # The name of mysql service
  mysql-database-name: rateme_swtp # The name of the database used by the demo app
  mysql-user-username: custom # A new created user for the demo app
  mysql-db-url: jdbc:mysql://database-service:3306/rateme_swtp
