apiVersion: v1
kind: Service
metadata:
  name: helm-{{ .Chart.Name }}-service
spec:
  selector:
    app: helm-{{ .Chart.Name }}
  type: {{ .Values.serviceType }}
  ports:
    - protocol: TCP
      port: {{ .Values.targetPort }}
      name: httpui
      targetPort: {{ .Values.targetPort }}
