scrape_configs:
  - job_name: "springboot"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 3s
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "My Spring Boot Application"
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
