ingress:
  name: rateme-nextgen-ingress
  ingressClass: gce

uiService:
  name: helm-ui-service
  port: 80

backendService:
  name: helm-backend-service
  port: 8080

clusterIssuer:
  name: letsencrypt-production
  email: rateme-nextgen@noreply.github.com
  server: https://acme-v02.api.letsencrypt.org/directory
  privateKeySecretRef:
    name: cert-manager-acme
  ingressClass: gce