apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.namespace}}-secret-store
  namespace: {{ .Values.namespace }}
spec:
  provider:
    gcpsm:
      projectID: rateme-nextgen #GCP projectID
      auth:
        workloadIdentity:
          clusterLocation: us-central1-c
          clusterName: rateme-nextgen-cluster
          serviceAccountRef:
            name: {{ .Values.namespace }}-service-account #KSA_NAME
