apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  labels:
    app: helm-{{ .Chart.Name }}
  annotations:
    meta.helm.sh/release-name: "ui-release-0.1"
data:
  apiConfig.js: {{ .Values.apiConfig }}