mysql-config-map:
  mysql-server: database-service
  mysql-database-name: rateme_swtp
  mysql-user-username: custom
  mysql-db-url: jdbc:mysql://database-service:3306/rateme_swtp


mysql-pass:
  mysql-root-password: 
  mysql-user-password: 


mysql-pvc:
  storageSize: 1Gi

database-deployment:
  image: backend-0.1.0-beta
  livenessProbe:
    tcpSocketPort: 3306
  containerPort: 3306

database-service:
  clusterIP: None
  servicePort: 3306