apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-{{ .Chart.Name }}
  labels:
    app: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: {{ include "backend.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          env:
            - name: SPRING_DATASOURCE_USERNAME
              # valueFrom:
              #   secretKeyRef:
              #     name: db-security
              #     key: user
              value: myuser
            - name: SPRING_DATASOURCE_PASSWORD
              # valueFrom:
              #   secretKeyRef:
              #     name: db-security
              #     key: password
              value: test
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://helm-database-service:3306/rateme_swtp