apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-backend
  namespace: dev
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-secret
            key: secret-access-credentials
      projectID: rateme-nextgen
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: gcp-external-secret
  namespace: dev
spec:
  secretStoreRef:
    kind: SecretStore
    name: gcp-backend
  target:
    name: secret-to-be-created
  data:
    - secretKey: password_file
      remoteRef:
        key: mysecret
