apiVersion: apps/v1
kind: Deployment
metadata:
  name: helm-{{ .Chart.Name }}
  labels:
    app: helm-{{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helm-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: helm-{{ .Chart.Name }}
    spec:
      containers:
        - name: backend-container
          image: {{ include "backend.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: {{ .Values.configMap.usernameKey }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.name }}
                  key: {{ .Values.secret.passwordKey }}
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMap.name }}
                  key: {{ .Values.configMap.dbURLKey }}
            - name: MYSQL_HOST
              value: {{ .Values.mysqlHost }}
