version: "3.8"

networks:
  monitoring:
    driver: bridge

services:
  app:
    image: app
    build:
      context: .
      dockerfile: "Dockerfile.backend"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - 8080:8080
  frontend:
    build:
      context: .
      dockerfile: "Dockerfile.ui"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - 8082:80
