version: "3.8"

networks:
  monitoring:
    driver: bridge

services:
  app:
    image: app
    build:
      context: .
      dockerfile: "Dockerfile.backend"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - 8080:8080
  frontend:
    build:
      context: .
      dockerfile: "Dockerfile.ui"
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    ports:
      - 8082:80
  database:
    build:
      context: ./database
      dockerfile: Dockerfile.database
    image: ratemedb:latest
    volumes:
      - ./database/DbVolume:/var/lib/mysql
      - ./database/config:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=rateme_swtp
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - "3306:3306"
