FROM openjdk:17-alpine

WORKDIR /app

COPY target/*.jar app.jar
COPY src/main/resources/application.properties /app/application.properties

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar", "--spring.config.location=file:/app/application.properties"]

