FROM openjdk:17-alpine

WORKDIR /app

COPY target/*.jar app.jar
COPY src/main/resources/application.properties /app/application.properties

EXPOSE 8080
RUN addgroup --system --gid 1002 app && adduser --system --uid 1002 --gid 1002 appuser
USER 1002

ENTRYPOINT ["java", "-jar", "app.jar", "--spring.config.location=file:/app/application.properties"]

