name: Maven Docker Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  push-docker-images:
    permissions: write-all
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./rateme"
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Get git tag"
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG=$TAG" >> $GITHUB_ENV

        env:
          TAG: ${{ steps.git_tag.outputs.tag }}

      - name: "Build Tag Push Frontend Image"
        run: |
          docker build -t rateme-nextgen-ui:$TAG -f Dockerfile.ui .
          docker tag rateme-nextgen-ui:$TAG ${{ secrets.REGISTRY }}/${{ secrets.PIDUSER }}/rateme-nextgen-ui:$TAG
          docker push ${{ secrets.REGISTRY }}/${{ secrets.PIDUSER }}/rateme-nextgen-ui:$TAG

      - name: "Build Tag Push Backend Image"
        run: |
          docker build -t rateme-nextgen-backend:$TAG -f Dockerfile.backend .
          docker tag rateme-nextgen-backend:$TAG ${{ secrets.REGISTRY }}/${{ secrets.PIDUSER }}/rateme-nextgen-backend:$TAG
          docker push ${{ secrets.REGISTRY }}/${{ secrets.PIDUSER }}/rateme-nextgen-backend:$TAG

      - name: "Build Tag Push Database Image"
        run: |
          docker build -t rateme-nextgen-database:$TAG -f Dockerfile.database .
          docker tag rateme-nextgen-database:$TAG ${{ secrets.REGISTRY }}/${{ secrets.PIDUSER }}/rateme-nextgen-database:$TAG
          docker push ${{ secrets.REGISTRY }}/${{ secrets.PIDUSER }}/rateme-nextgen-database:$TAG
