name: Deploy Images to GHCR

on:
  push:
    branches:
      - feature/*
  workflow_dispatch:
jobs:
  push-docker-images:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./rateme"
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build Frontend Image"
        run: |
          docker build -t rateme-nextgen-ui:latest -f Dockerfile.ui .
          docker tag rateme-nextgen-ui:latest ghcr.io/goldjns/rateme-nextgen-ui:latest
          docker push ghcr.io/goldjns/rateme-nextgen-ui:latest

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: "Build Backend Image"
        run: |
          docker build -t rateme-nextgen-backend:latest -f Dockerfile.backend .
          docker tag rateme-nextgen-backend:latest ghcr.io/goldjns/rateme-nextgen:latest
          docker push ghcr.io/goldjns/rateme-nextgen-backend:latest
           - name: "Build Frontend Image"

      - name: "Build Database Image"
        run: |
          docker build -t rateme-nextgen-database:latest -f Dockerfile.database .
          docker tag rateme-nextgen-database:latest ghcr.io/goldjns/rateme-nextgen-database:latest
          docker push ghcr.io/goldjns/rateme-nextgen-database:latest
