name: Deploy Images to GHCR

on:
  push:
    branches:
      - feature/*
  workflow_dispatch:
jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./rateme"
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build Frontend Image"
        run: |
          docker build -t rateme-nextgen:latest -f Dockerfile.ui .
          docker push ghcr.io/goldjns/rateme-nextgen:latest
