name: Maven Docker Build

on:
  push:
    branches:
      - feature/*
  workflow_dispatch:
jobs:
  push-docker-images:
    permissions: write-all
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./rateme"
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build Tag Push Frontend Image"
        run: |
          TAG=$(git describe --tags --abbrev=0)
          docker build -t rateme-nextgen-ui:$TAG -f Dockerfile.ui .
          docker tag rateme-nextgen-ui:$TAG ${{ secrets.REGISTRY }}/${{ secrets.PIDUSER }}/rateme-nextgen-ui:$TAG
          docker push ${{ secrets.REGISTRY }}/${{ secrets.PIDUSER }}/rateme-nextgen-ui:$TAG

      - name: "Build Tag Push Backend Image"
        run: |
          docker build -t rateme-nextgen-backend:latest -f Dockerfile.backend .
          docker tag rateme-nextgen-backend:latest ${{ secrets.REGISTRY }}/${{ secrets.PIDUSER }}/rateme-nextgen-database:latest
          docker push ${{ secrets.REGISTRY }}/${{ secrets.PIDUSER }}/rateme-nextgen-backend:latest

      - name: "Build Tag Push Database Image"
        run: |
          docker build -t rateme-nextgen-database:latest -f Dockerfile.database .
          docker tag rateme-nextgen-database:latest ${{ secrets.REGISTRY }}/${{ secrets.PIDUSER }}/rateme-nextgen-database:latest
          docker push ${{ secrets.REGISTRY }}/${{ secrets.PIDUSER }}/rateme-nextgen-database:latest
