name: Helm deploy

on:
  push:
    branches:
      - main
      - feature/*
      - fix/*
      - chore/*
  workflow_dispatch:
jobs:
  deploy-dev-job:
    runs-on: ubuntu-latest
    environment: dev-deploy
    env:
      NAMESPACE: ${{ vars.NAMESPACE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Deploying to dev environment
        uses: "./.github/template/deploy"
        with:
          environment: dev-deploy

  deploy-prod-job:
    runs-on: ubuntu-latest
    environment: prod-deploy
    env:
      NAMESPACE: ${{ vars.NAMESPACE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - name: Deploying to prod environment
        uses: "./.github/template/deploy"
        with:
          environment: prod-deploy
