name: Release

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "*.md"
jobs:
  helm-deploy:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: ./deployment/deployAll.sh ${NAMESPACE}
          kubeconfig: "${{ secrets.KUBECONFIG }}"
          overrule_existing_kubeconfig: "true"
