name: "Terraform Destroy"

on:
  push:
    branches:
      - main
      - feature/*
      - fix/*
      - chore/*
      - refactor/*
  workflow_dispatch:
permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Wait for Approval
        if: always()
        uses: "technosophos/wait-for-input@v1"
        with:
          message: "Please review the changes and approve to destroy the infrastructure"
          timeout_seconds: 604800 # Adjust timeout as needed

      - name: Terraform Destroy
        run: |
          echo "** Running Terraform Destroy**"
          terraform destroy -lock=false -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
